networks:
  docker-net:
    name: docker-net
    driver: bridge

volumes:
  hadoop_datanode:
  hadoop_namenode:

services:
  # spark:
  #   image: docker.io/bitnami/spark:3.5
  #   container_name: spark-master
  #   hostname: spark
  #   env_file:
  #     - .env
  #   environment:
  #     - SPARK_MODE=master
  #     - SPARK_RPC_AUTHENTICATION_ENABLED=no
  #     - SPARK_RPC_ENCRYPTION_ENABLED=no
  #     - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
  #     - SPARK_SSL_ENABLED=no
  #     - SPARK_USER=spark
  #     - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
  #   ports:
  #     - '8080:8080'
  #     - '7077:7077'
  #     - '4040:4040'
  #   networks:
  #     - docker-net

  # spark-worker:
  #   image: docker.io/bitnami/spark:3.5
  #   container_name: spark-worker
  #   env_file:
  #     - .env
  #   environment:
  #     - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
  #   ports:
  #     - 8081:8081
  #   networks:
  #     - docker-net

  namenode:
    container_name: namenode
    image: apache/hadoop:3
    hostname: namenode
    command: ["hdfs", "namenode"]
    ports:
      - 9870:9870
      - 8020:8020
      - 9000:9000
    env_file:
      - .env
    environment:
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-hadoop/dfs/name"
    volumes:
      - ./namenode:/tmp/hadoop-root/dfs/name
      - hadoop_namenode:/tmp/hadoop-root/dfs/name
    networks:
      - docker-net

  datanode:
    image: apache/hadoop:3
    container_name: datanode
    hostname: datanode 
    command: ["hdfs", "datanode"]
    ports:
      - 9864:9864
      - 9866:9866
    expose:
      - 50010
    env_file:
      - .env
    volumes:
      - hadoop_datanode:/tmp/hadoop-root/dfs/data
      - ./datanode:/tmp/hadoop-root/dfs/data
    networks:
      - docker-net

  resourcemanager:
    image: apache/hadoop:3
    hostname: resourcemanager
    command: ["yarn", "resourcemanager"]
    ports:
       - 8088:8088
    env_file:
      - .env
    volumes:
      - ./test.sh:/opt/test.sh
    networks:
      - docker-net

  nodemanager:
    image: apache/hadoop:3
    command: ["yarn", "nodemanager"]
    env_file:
      - .env
    ports:
      - 8188:8188
    networks:
      - docker-net

  notebook:
    container_name: notebook
    build:
      context: ./notebook
    volumes:
      - ${PWD}/workspace:/home/jovyan/work
    ports:
      - 8888:8888
    environment:
      - JUPYTER_TOKEN=pass
    command: start-notebook.sh
    user: root
    networks:
        - docker-net


  # dremio:
  #   container_name: dremio
  #   hostname: dremio
  #   image: dremio/dremio-oss
  #   ports:
  #     - 9047:9047
  #     - 31010:31010
  #     - 45678:45678
  #   volumes:
  #     - db-data:/var/lib/dremio
  #     - ./localFiles:/localFiles
  #     - db-data:/opt/dremio/data
  #   networks:
  #     - docker-net
